# Generated by Django 5.2 on 2026-03-09 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0005_remove_episode_thumbnail_url_episode_thumbnail_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FanClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='fan_club_covers/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('requirements_text', models.TextField(blank=True, help_text='Описание того, что нужно предоставить для вступления')),
                ('application_questions', models.JSONField(blank=True, default=list, help_text="Список вопросов: [{'id': 'q1', 'text': 'Вопрос?'}]")),
                ('max_application_photos', models.PositiveIntegerField(default=3, help_text='Макс. фото в заявке')),
                ('max_club_photos', models.PositiveIntegerField(default=20, help_text='Макс. фото в галерее клуба')),
                ('allowed_file_types', models.CharField(default='jpg,jpeg,png', help_text='Разрешённые расширения', max_length=255)),
                ('max_file_size_mb', models.PositiveIntegerField(default=5, help_text='Макс. размер файла в МБ')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fan_clubs', to='cinema.chapter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fan_clubs', to=settings.AUTH_USER_MODEL)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fan_clubs', to='cinema.franchise')),
            ],
            options={
                'verbose_name': 'Фан-клуб',
                'verbose_name_plural': 'Фан-клубы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FanClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('member', 'Участник')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Участник'), ('rejected', 'Отказано'), ('banned', 'Заблокирован')], default='pending', max_length=20)),
                ('application_data', models.JSONField(blank=True, default=dict, help_text='Ответы на вопросы')),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='fan_clubs.fanclub')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_club_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Членство в клубе',
                'verbose_name_plural': 'Членство в клубах',
                'ordering': ['-role', '-joined_at', '-applied_at'],
                'unique_together': {('user', 'club')},
            },
        ),
        migrations.CreateModel(
            name='FanClubPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='fan_club_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fan_clubs.fanclub')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_club_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Фото клуба',
                'verbose_name_plural': 'Фото клуба',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FanClubApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='fan_club_applications/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('moved_to_club_gallery', models.BooleanField(default=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_attachments', to='fan_clubs.fanclubmembership')),
                ('club_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_attachments', to='fan_clubs.fanclubphoto')),
            ],
            options={
                'verbose_name': 'Вложение заявки',
                'verbose_name_plural': 'Вложения заявок',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
