# Generated by Django 5.2 on 2026-03-25 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_chapter_options_and_more'),
        ('fan_clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanclub',
            name='allowed_file_types',
            field=models.CharField(default='jpg,jpeg,png', help_text='Разрешённые расширения', max_length=255, verbose_name='Разрешённые типы файлов'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='application_questions',
            field=models.JSONField(blank=True, default=list, help_text="Список вопросов: [{'id': 'q1', 'text': 'Вопрос?'}]", verbose_name='Вопросы заявки'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fan_clubs', to='cinema.chapter', verbose_name='Глава'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='fan_club_covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fan_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fan_clubs', to='cinema.franchise', verbose_name='Франшиза'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='max_application_photos',
            field=models.PositiveIntegerField(default=3, help_text='Макс. фото в заявке', verbose_name='Макс. фото в заявке'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='max_club_photos',
            field=models.PositiveIntegerField(default=20, help_text='Макс. фото в галерее клуба', verbose_name='Макс. фото в галерее'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='max_file_size_mb',
            field=models.PositiveIntegerField(default=5, help_text='Макс. размер файла в МБ', verbose_name='Макс. размер файла (МБ)'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='requirements_text',
            field=models.TextField(blank=True, help_text='Описание того, что нужно предоставить для вступления', verbose_name='Требования для вступления'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='fanclubapplicationattachment',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='fanclubapplicationattachment',
            name='club_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_attachments', to='fan_clubs.fanclubphoto', verbose_name='Фото в галерее'),
        ),
        migrations.AlterField(
            model_name='fanclubapplicationattachment',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла'),
        ),
        migrations.AlterField(
            model_name='fanclubapplicationattachment',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_attachments', to='fan_clubs.fanclubmembership', verbose_name='Членство'),
        ),
        migrations.AlterField(
            model_name='fanclubapplicationattachment',
            name='moved_to_club_gallery',
            field=models.BooleanField(default=False, verbose_name='Перенесено в галерею'),
        ),
        migrations.AlterField(
            model_name='fanclubapplicationattachment',
            name='photo',
            field=models.ImageField(upload_to='fan_club_applications/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='fanclubapplicationattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='fanclubmembership',
            name='application_data',
            field=models.JSONField(blank=True, default=dict, help_text='Ответы на вопросы', verbose_name='Данные заявки'),
        ),
        migrations.AlterField(
            model_name='fanclubmembership',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки'),
        ),
        migrations.AlterField(
            model_name='fanclubmembership',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='fan_clubs.fanclub', verbose_name='Клуб'),
        ),
        migrations.AlterField(
            model_name='fanclubmembership',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата вступления'),
        ),
        migrations.AlterField(
            model_name='fanclubmembership',
            name='review_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий проверки'),
        ),
        migrations.AlterField(
            model_name='fanclubmembership',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AlterField(
            model_name='fanclubmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('member', 'Участник')], default='member', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='fanclubmembership',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Участник'), ('rejected', 'Отказано'), ('banned', 'Заблокирован')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='fanclubmembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='fanclubmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_club_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='fanclubphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='fanclubphoto',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fan_clubs.fanclub', verbose_name='Клуб'),
        ),
        migrations.AlterField(
            model_name='fanclubphoto',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла'),
        ),
        migrations.AlterField(
            model_name='fanclubphoto',
            name='photo',
            field=models.ImageField(upload_to='fan_club_gallery/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='fanclubphoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='fanclubphoto',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_club_photos', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
    ]
