# Generated by Django 5.2 on 2026-03-25 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_chapter_options_and_more'),
        ('fan_clubs', '0003_alter_fanclub_franchise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanclub',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fan_clubs', to='cinema.franchise', verbose_name='Франшиза'),
        ),
    ]
