# Generated by Django 5.2 on 2026-06-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_clubs', '0004_alter_fanclub_franchise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanclub',
            name='allowed_file_types',
            field=models.CharField(default='jpg,jpeg,png', max_length=255, verbose_name='Разрешённые типы файлов'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='max_application_photos',
            field=models.PositiveIntegerField(default=3, verbose_name='Макс. фото в заявке'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='max_club_photos',
            field=models.PositiveIntegerField(default=20, verbose_name='Макс. фото в галерее'),
        ),
        migrations.AlterField(
            model_name='fanclub',
            name='max_file_size_mb',
            field=models.PositiveIntegerField(default=5, verbose_name='Макс. размер файла (МБ)'),
        ),
    ]
