# Generated by Django 5.2 on 2025-05-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='userpaymentmethod',
            name='is_active',
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
