# Generated by Django 5.2 on 2025-05-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_delete_test_remove_chapter_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic_url',
        ),
        migrations.AddField(
            model_name='chapter',
            name='franchise_relation',
            field=models.CharField(blank=True, choices=[('main', 'Основная история'), ('spinoff', 'Спин-офф'), ('side', 'Побочная история'), ('other', 'Другое')], help_text='Тип связи главы с франшизой (например, основная история, спин-офф и т.д.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='chapter_posters/'),
        ),
        migrations.AddField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='episode_videos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_pics/'),
        ),
    ]
