# Generated by Django 5.2 on 2025-05-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_remove_chapter_poster_url_remove_episode_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='episode',
            name='thumbnail_img',
            field=models.ImageField(blank=True, null=True, upload_to='episode_thumbnail_imgs/'),
        ),
    ]
