# Generated by Django 5.2 on 2026-03-25 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cinema', '0005_remove_episode_thumbnail_url_episode_thumbnail_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_number'], 'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
        migrations.AlterModelOptions(
            name='chapterpersonrole',
            options={'verbose_name': 'Роль в главе', 'verbose_name_plural': 'Роли в главах'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['episode_number'], 'verbose_name': 'Эпизод', 'verbose_name_plural': 'Эпизоды'},
        ),
        migrations.AlterModelOptions(
            name='franchise',
            options={'verbose_name': 'Франшиза', 'verbose_name_plural': 'Франшизы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Персона', 'verbose_name_plural': 'Персоны'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['title'], 'verbose_name': 'Плейлист', 'verbose_name_plural': 'Плейлисты'},
        ),
        migrations.AlterModelOptions(
            name='playlistchapter',
            options={'ordering': ['-added_at'], 'verbose_name': 'Глава в плейлисте', 'verbose_name_plural': 'Главы в плейлистах'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userpaymentmethod',
            options={'verbose_name': 'Способ оплаты', 'verbose_name_plural': 'Способы оплаты'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'Подписка пользователя', 'verbose_name_plural': 'Подписки пользователей'},
        ),
        migrations.AlterModelOptions(
            name='viewhistory',
            options={'ordering': ['-viewed_at'], 'verbose_name': 'История просмотра', 'verbose_name_plural': 'Истории просмотров'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='age_rating',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возрастной рейтинг'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер главы'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content_type',
            field=models.CharField(blank=True, choices=[('movie', 'Фильм'), ('series', 'Сериал')], max_length=20, null=True, verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='cinema.franchise', verbose_name='Франшиза'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='franchise_relation',
            field=models.CharField(blank=True, choices=[('main', 'Основная история'), ('spinoff', 'Спин-офф'), ('side', 'Побочная история'), ('other', 'Другое')], help_text='Тип связи главы с франшизой (например, основная история, спин-офф и т.д.)', max_length=20, null=True, verbose_name='Связь с франшизой'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='chapters', to='cinema.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='chapters', through='cinema.ChapterPersonRole', to='cinema.person', verbose_name='Персоны'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='chapter_posters/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='rating_cache',
            field=models.FloatField(default=0.0, verbose_name='Кэш рейтинга'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='required_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.subscription', verbose_name='Требуемая подписка'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на трейлер'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='chapterpersonrole',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_roles', to='cinema.chapter', verbose_name='Глава'),
        ),
        migrations.AlterField(
            model_name='chapterpersonrole',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_roles', to='cinema.person', verbose_name='Персона'),
        ),
        migrations.AlterField(
            model_name='chapterpersonrole',
            name='role',
            field=models.CharField(blank=True, choices=[('actor', 'Актер'), ('director', 'Режиссер'), ('screenwriter', 'Сценарист'), ('producer', 'Продюсер'), ('editor', 'Монтажер')], max_length=20, null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cinema.chapter', verbose_name='Глава'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='cinema.chapter', verbose_name='Глава'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер эпизода'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='thumbnail_img',
            field=models.ImageField(blank=True, null=True, upload_to='episode_thumbnail_imgs/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='episode_videos/', verbose_name='Видеофайл'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на обложку'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичный'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='playlistchapter',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='playlistchapter',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='cinema.chapter', verbose_name='Глава'),
        ),
        migrations.AlterField(
            model_name='playlistchapter',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='playlistchapter',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_chapters', to='cinema.playlist', verbose_name='Плейлист'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='cinema.chapter', verbose_name='Глава'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='review',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cinema.chapter', verbose_name='Глава'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration_days',
            field=models.IntegerField(verbose_name='Длительность (дни)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (USD)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, к которым принадлежит этот пользователь.', related_name='custom_user_set', to='auth.group', verbose_name='группы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код входа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_pics/', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Специфические права для этого пользователя.', related_name='custom_user_set', to='auth.permission', verbose_name='права пользователя'),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='card_brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Платежная система'),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='card_expiry_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Месяц истечения'),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='card_expiry_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год истечения'),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='masked_card_number',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Маска номера карты'),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Банковская карта'), ('paypal', 'PayPal'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('yoo_money', 'ЮMoney'), ('sbp', 'СБП')], max_length=20, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='provider_id',
            field=models.CharField(max_length=255, verbose_name='ID провайдера'),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Действительно до'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='auto_renew',
            field=models.BooleanField(default=False, verbose_name='Автопродление'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='payment_methods',
            field=models.ManyToManyField(related_name='subscriptions', to='cinema.userpaymentmethod', verbose_name='Способы оплаты'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='cinema.subscription', verbose_name='Тип подписки'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='cinema.chapter', verbose_name='Глава'),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра'),
        ),
    ]
