# Generated by Django 5.2 on 2026-06-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AlterUniqueTogether(
            name='chapterpersonrole',
            unique_together={('chapter', 'person', 'role')},
        ),
    ]
