# Generated by Django 5.2 on 2026-06-15 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_delete_testmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Сома-кола', help_text='Название компании, отображается в футере', max_length=255, verbose_name='Название компании')),
                ('copyright_text', models.CharField(default='© 2003-2024 Не_Кинопоиск', help_text='Текст копирайта в футере', max_length=255, verbose_name='Текст копирайта')),
                ('age_rating', models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], default='18+', max_length=10, verbose_name='Возрастной рейтинг')),
                ('support_text', models.CharField(blank=True, default='Мы всегда готовы вам помочь.', max_length=255, verbose_name='Текст поддержки')),
                ('support_button_text', models.CharField(blank=True, default='Задать вопрос', max_length=100, verbose_name='Текст кнопки поддержки')),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='{"vk": "...", "telegram": "...", "youtube": "...", "ok": "..."}', verbose_name='Ссылки на социальные сети')),
                ('footer_poem', models.TextField(blank=True, default='', help_text='Многострочный текст, отображается в футере', verbose_name='Текст в футере (поэма)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_settings_updates', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем')),
            ],
            options={
                'verbose_name': 'Настройки компании',
                'verbose_name_plural': 'Настройки компании',
            },
        ),
    ]
